In [1]:
import numpy as np

In [2]:
class LogisticRegressionGD(object):
    """Logistic Regression Classifier using gradient descent.
    
    Parameters
    ------------
    learning_rate : float
      Learning rate (between 0.0 and 1.0)
    max_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight
      initialization.

    Attributes
    -----------
    weights_ : 1d-array
      Weights after fitting.
    cost_ : list
      Sum-of-squares cost function value in each epoch.

    """
    def __init__(self, learning_rate=0.05, max_iter=100, random_state=1):
        self.learning_rate = learning_rate
        self.max_iter = max_iter
        self.random_state = random_state

    def fit(self, X, y):
        """ Fit training data.

        Parameters
        ----------
        X : {array-like}, shape = [n_samples, n_features]
          Training vectors, where n_samples is the number of samples and
          n_features is the number of features.
        y : array-like, shape = [n_samples]
          Target values.

        Returns
        -------
        self : object

        """
        random_gen = np.random.RandomState(self.random_state)
        self.weights_ = random_gen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
        self.cost_ = []

        for i in range(self.max_iter):
            weight_input = self.weight_input(X)
            output = self.activation(weight_input)
            errors = (y - output)
            self.weights_[1:] += self.learning_rate * X.T.dot(errors)
            self.weights_[0] += self.learning_rate * errors.sum()         
            cost = -y.dot(np.log(output)) - ((1 - y).dot(np.log(1 - output)))
            self.cost_.append(cost)
        return self
    
    def weight_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weights_[1:]) + self.weights_[0]

    def activation(self, z):
        """Compute logistic sigmoid activation"""
        return 1. / (1. + np.exp(-np.clip(z, -250, 250)))

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.weight_input(X) >= 0.0, 1, 0)
    def score(self,X,y):
        """Return sccuracy score"""
        y_pred = self.predict(X)
        corr_pred = (y_pred == y).sum()
        return corr_pred / float(len(y))

In [3]:
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
X = iris.data[:, [1, 3]]
y = iris.target

In [4]:
X_train = X[(y==0) | (y==1)]
y_train = y[(y==0) | (y==1)]

In [6]:
log_model = LogisticRegressionGD(learning_rate=0.05, max_iter=100, random_state=1)

In [7]:
log_model.fit(X_train,y_train)

In [8]:
log_model.predict(X_train)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
log_model.score(X_train,y_train)

1.0

In [11]:
log_model.weights_

array([  1.31840233,  -4.26654664,  14.73659972])

In [12]:
log_model.cost_

[69.359162069304716,
 49.619112531317484,
 539.01505486854046,
 717.25190248195827,
 295.39226015698426,
 757.73472147265215,
 73.680263164582897,
 434.27078733078679,
 249.39749092342453,
 466.01307563385825,
 55.509398271008436,
 18.904491801856395,
 0.094401901287005999,
 0.093005942997530372,
 0.091721699129528017,
 0.090538643507162939,
 0.089447433917992467,
 0.088439751968274791,
 0.087508168415439347,
 0.086646029351032577,
 0.085847359544461294,
 0.085106779986510478,
 0.084419437242314849,
 0.083780942673289338,
 0.083187319944299537,
 0.082634959517045664,
 0.082120579058870727,
 0.081641188880512222,
 0.081194061665450484,
 0.080776705875199042,
 0.080386842314259091,
 0.080022383420265727,
 0.079681414912279341,
 0.079362179486055229,
 0.079063062291580805,
 0.078782577967038595,
 0.078519359035733566,
 0.078272145499948445,
 0.07803977548863511,
 0.077821176835389971,
 0.077615359479674184,
 0.077421408598276439,
 0.07723847838608322,
 0.077065786415431894,
 0.07690260851